Adds postgres as variant to mysql
Adds setting of OWNCLOUD_DB variable in deploy hook.
Adds postgres branch in autoconfig.php based on OWNCLOUD_DB.
Adds command to install with postgres on OO into README.md.

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -1,4 +1,5 @@
 #!/bin/bash
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
 dest_dir=${OPENSHIFT_DATA_DIR}current
 current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
@@ -25,20 +26,27 @@ ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php
 
 set -e
 
-echo "Checking MySQL database..."
-
-if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
-then
-    echo 1>&2
-    echo "Could not find mysql database.  Please run:" 1>&2
-    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
-    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
-    echo 1>&2
+if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
+  export OWNCLOUD_DB="postgresql"
 fi
 
-if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
-then 
-   exit 5
+if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
+  export OWNCLOUD_DB="mysql"
+fi
+
+if [ -z "$OWNCLOUD_DB" ]; then
+  echo 1>&2
+  echo "Could not find the database cartridge.  Please run:" 1>&2
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
+  echo "or"
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
+  echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+  echo 1>&2
+  exit 5
+else
+  if [ "$(type -t set_env_var)" == "function" ]; then
+    set_env_var 'OWNCLOUD_DB' $OWNCLOUD_DB $OPENSHIFT_HOMEDIR/.env/user_vars
+  fi
 fi
 
 echo "Completed deploy."
